// <auto-generated />
using GrowthPulse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrowthPulse.Migrations
{
    [DbContext(typeof(GoalDetailContext))]
    partial class GoalDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GrowthPulse.Models.GoalDetail", b =>
                {
                    b.Property<int>("GoalDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalDetailId"), 1L, 1);

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoalOwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoalSetDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("GoalDetailId");

                    b.ToTable("GoalDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
